// get all the cards from the thing
// all the cards to put into base cards, fuck this is going to be a bad file,

const allCardKeys = [
  "Apostles of the Deep - 0",
  "Apostles of the Deep - 1",
  "Apostles of the Deep - 8",
  "Battle Pigs - 0",
  "Battle Pigs - 1",
  "Battle Pigs - 2",
  "Battle Pigs - 3",
  "Battle Pigs - 4",
  "Bone and Darkness AI - 0",
  "Bone and Darkness AI - 1",
  "Bone and Darkness AI - 2",
  "Bone and Darkness AI - 3",
  "Bone and Darkness AI - 4",
  "Kingdoms of Akadh - 0",
  "Kingdoms of Akadh - 1",
  "Kingdoms of Akadh - 2",
  "Kingdoms of Akadh - 3",
  "Lostwood Enclave - 0",
  "Lostwood Enclave - 1",
  "Lostwood Enclave - 2",
  "Lostwood Enclave - 3",
  "Moldorf Expedition - 0",
  "Moldorf Expedition - 1",
  "Moldorf Expedition - 2",
  "Moldorf Expedition - 3",
  "Singular Champions 1 - 0",
  "Singular Champions 1 - 2",
  "Singular Champions 1 - 3",
  "Singular Champions 1 - 4",
  "Singular Champions 1 - 6",
  "Singular Champions 1 - 8",
  "Singular Champions 1 - 10",
  "Singular Champions 2 - 0",
  "Singular Champions 2 - 2",
  "Singular Champions 2 - 4",
  "Singular Champions 2 - 6",
  "Singular Champions 2 - 8",
  "Storms of Kural cards - 0",
  "Storms of Kural cards - 1",
  "Storms of Kural cards - 2",
  "Storms of Kural cards - 3",
  "Storms of Kural cards - 4",
  "Storms of Kural cards - 5",
  "Storms of Kural cards - 6",
  "Storms of Kural cards - 7",
  "Storms of Kural cards - 8",
  "Storms of Kural cards - 9",
  "Storms of Kural cards - 10",
  "Storms of Kural cards - 11",
  "Storms of Kural cards - 12",
  "Storms of Kural cards - 13",
  "Storms of Kural cards - 14",
  "Storms of Kural cards - 15",
  "Storms of Kural cards - 16",
  "Storms of Kural cards - 17",
  "Storms of Kural cards - 18",
  "Storms of Kural cards - 19",
  "Storms of Kural cards - 20",
  "Storms of Kural cards - 21",
  "Storms of Kural cards - 22",
  "Storms of Kural cards - 23",
  "Storms of Kural cards - 24",
  "Storms of Kural cards - 25",
  "Storms of Kural cards - 26",
  "Storms of Kural cards - 27",
  "Storms of Kural cards - 28",
  "Storms of Kural cards - 29",
  "Storms of Kural cards - 30",
  "Storms of Kural cards - 31",
  "Storms of Kural cards - 32",
  "Storms of Kural cards - 33",
  "Storms of Kural cards - 34",
  "Storms of Kural cards - 35",
  "Storms of Kural cards - 36",
  "Storms of Kural cards - 37",
  "Temple of Justice - 0",
  "Temple of Justice - 1",
  "Temple of Justice - 2",
  "Temple of Justice - 3",
  "The Lone Guard 19 - 0",
  "The Lone Guard 19 - 1",
  "The Lone Guard 19 - 2",
  "The Lone Guard 19 - 3",
  "Wretched Hive - 0",
  "Wretched Hive - 1",
  "Wretched Hive - 2",
  "Wretched Hive - 3",
  "The Wilderkin - 0",
  "The Wilderkin - 1",
  "The Wilderkin - 2",
  "The Wilderkin - 3",
  "Singular Champions 3 - 10",
  "Singular Champions 3 - 0",
  "Singular Champions 3 - 2",
  "Singular Champions 3 - 4",
  "Singular Champions 3 - 6",
  "Singular Champions 3 - 7",
  "Singular Champions 3 - 8",
  "Singular Champions 4 - 10",
  "Singular Champions 4 - 0",
  "Singular Champions 4 - 2",
  "Singular Champions 4 - 4",
  "Singular Champions 4 - 6",
  "Singular Champions 4 - 8",
  "Aug Suul - 0",
  "Aug Suul - 1",
  "Aug Suul - 2",
  "Aug Suul - 10",
  "Aug Suul - 12",
  "Aug Suul - 14",
  "Aug Suul - 15"];